name: _Destroy_ infrastructure
on:
  workflow_dispatch:

jobs:
  destroy2:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: az login
        shell: bash
        run: az login --service-principal -u ${{ env.ARM_CLIENT_ID }} -p ${{ env.ARM_CLIENT_SECRET }} --tenant ${{ env.ARM_TENANT_ID }}

      - name: Make Storage Account network public accessable
        shell: bash
        run: |
          sa=$(az storage account list --query "[].name" --output tsv)

          for row in $sa
          do
            tmpName=$(echo $row | sed -e 's/\r//g')
            az storage account update --name $tmpName --default-action "Allow"
          done

      - name: Terraform init
        run: terraform init

      #- name: Terraform destroy
      #  run: terraform destroy -auto-approve -input=false
