name: Enable Public access Storage and Keyvault
on:
  workflow_dispatch:

jobs:
  enablePublic:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: az login
        shell: bash
        run: az login --service-principal -u ${{ env.ARM_CLIENT_ID }} -p ${{ env.ARM_CLIENT_SECRET }} --tenant ${{ env.ARM_TENANT_ID }}

      - name: Make Storage Account network public accessable
        shell: bash
        run: |
          sa=$(az storage account list --query "[].name" --output tsv)

          for row in $sa
          do
            name=$(echo $row | sed -e 's/\r//g')
            echo "Enable access Storage account : $name"
            az storage account update --name $name --default-action "Allow"
          done

      - name: Make Key Vault network public accessable
        shell: bash
        run: |
          kv=$(az keyvault list --query "[].{name:name,resourceGroup:resourceGroup}")

          for kv in $(echo "$kv" | jq -c '.[]'); do
            name=$(echo "$kv" | jq -r '.name')
            rg=$(echo "$kv" | jq -r '.resourceGroup')
            echo "Enable access Key Vault: $name in resourcegroup: $rg"
            az keyvault update --name $name --resource-group $rg --set properties.networkAcls.defaultAction=Allow
          done